# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'AdministratorAccountAdminUI.ui'
#
# Created by: PyQt5 UI code generator 5.15.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.

import sys
import json
from QDialog import myDialog
from PyQt5.QtWidgets import QApplication, QAbstractItemView, QHeaderView, QListWidget, QMessageBox
from PyQt5 import QtCore, QtGui, QtWidgets
from TcpClient import tcp_client_socket

from addAdmin import Ui_Dialog as addAdministrator


class Ui_dialog(object):
    def setupUi(self, dialog, administratorID, administratorData):
        self.administratorID = administratorID
        self.administratorNum = len(administratorData)
        self.data = administratorData
        self.dialog = dialog
        dialog.setObjectName("dialog")
        dialog.resize(630, 500)
        self.verticalLayout = QtWidgets.QVBoxLayout(dialog)

        self.label = QtWidgets.QLabel(dialog)
        font = QtGui.QFont()
        font.setPointSize(13)
        self.label.setFont(font)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.label.setGeometry(230,10,200,40)

        self.tableWidget = QtWidgets.QTableWidget(dialog)
        self.tableWidget.setMidLineWidth(-12)
        self.tableWidget.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.tableWidget.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.tableWidget.setObjectName("tableWidget")

        self.tableWidget.verticalHeader().setVisible(False)  # 隐藏垂直表头

        self.tableWidget.setColumnCount(4)
        self.tableWidget.setRowCount(self.administratorNum)
        item = QtWidgets.QTableWidgetItem()

        for i in range(self.administratorNum):
            self.tableWidget.setVerticalHeaderItem(i, item)
            item = QtWidgets.QTableWidgetItem()

        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()

        for i in range(self.administratorNum):
            for j in range(4):
                self.tableWidget.setItem(i, j, item)
                item = QtWidgets.QTableWidgetItem()


        self.tableWidget.setGeometry(20,60,600,345)

        self.pushButton = QtWidgets.QPushButton(dialog)
        self.pushButton.setObjectName("pushButton")
        self.pushButton.setGeometry(270,425,100,40)

        self.retranslateUi(dialog)
        self.tableWidget.cellClicked['int', 'int'].connect(self.deleteAdministrator)
        self.pushButton.clicked.connect(self.addAdministrator)

        QtCore.QMetaObject.connectSlotsByName(dialog)

    def retranslateUi(self, dialog):
        _translate = QtCore.QCoreApplication.translate
        dialog.setWindowTitle(_translate("dialog", "管理员账号管理"))
        self.label.setText(_translate("dialog", "管理员账号管理"))

        for i in range(self.administratorNum):
            item = self.tableWidget.verticalHeaderItem(i)
            item.setText(_translate("dialog", str(i+1)))

        item = self.tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("dialog", "管理员ID"))
        item = self.tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("dialog", "用户名"))
        item = self.tableWidget.horizontalHeaderItem(2)
        item.setText(_translate("dialog", "密码"))
        item = self.tableWidget.horizontalHeaderItem(3)
        item.setText(_translate("dialog", "删除管理员"))

        __sortingEnabled = self.tableWidget.isSortingEnabled()
        self.tableWidget.setSortingEnabled(False)

        for i in range(self.administratorNum):
            for j in range(3):
                item = self.tableWidget.item(i, j)
                item.setText(_translate("dialog", str(self.data[i][j])))
            item = self.tableWidget.item(i, 3)
            item.setText(_translate("dialog", "删除"))

        self.tableWidget.setSortingEnabled(__sortingEnabled)
        self.pushButton.setText(_translate("dialog", "添加管理员"))

    def deleteAdministrator(self, x, y):
        if y==3:
            isDel = QMessageBox.information(self.dialog, "提示", "是否确定删除管理员" + str(self.data[x][1]) +"？", QMessageBox.Yes|QMessageBox.No,QMessageBox.Yes)
            if isDel == QMessageBox.Yes:
                tcp_client_socket.send("818 " + self.administratorID + " " + str(self.data[x][0]))
                data_list_819 = tcp_client_socket.rec().split(" ")
                if(json.loads(data_list_819[1]) == 1):
                    del self.data[x]
                    self.tableWidget.removeRow(x)

    def addAdministrator(self):
        self.dialog.setEnabled(False)  # 设置本窗口无法选择
        form = myDialog()
        form.setWindowModality(2)  # 使本窗口无法选中
        ui = addAdministrator()
        ui.setupUi(form, self.dialog,self.administratorID)
        form.show()
        form.exec_()
        self.dialog.setEnabled(True)

if __name__ == "__main__":

    data=[[111111,"小红",123123],[2222222,"小白",234234],[333333,"小黑",345345]]

    app = QApplication(sys.argv)
    form = myDialog()
    ui = Ui_dialog()
    ui.setupUi(form, 12342, data)
    form.show()
    app.exec_()
    sys.exit()