# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Login.ui'
#
# Created by: PyQt5 UI code generator 5.15.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.
import sys

from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QApplication, QMessageBox, QLineEdit
import QDialog
from QDialog import MainDialog, myDialog
from TcpClient import TcpClientSocket

from MainUI import Ui_Dialog
from RegistrationUI import RegisDialog
from AdministratorsMainUI import Ui_Dialog as AdministratorsMainUI
from TcpClient import tcp_client_socket


class Login_Dialog(object):
    def setupUi(self, Dialog):
        self.form = Dialog

        Dialog.setObjectName("Dialog")
        Dialog.resize(407, 265)
        Dialog.setFixedSize(Dialog.width(), Dialog.height())
        Dialog.setStyleSheet("#Dialog{background-color: gainsboro;\n"
                             "border-image: url(icon/login.jpg);}")
        self.horizontalLayoutWidget = QtWidgets.QWidget(Dialog)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(120, 180, 171, 71))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.Login_button = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.Login_button.setEnabled(True)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(16)
        self.Login_button.setFont(font)
        self.Login_button.setStyleSheet(
            "QPushButton { background-color: rgb(125, 127, 255); border-radius: 3px; color: rgb(255, 255, 255); } QPushButton:hover { background-color: rgb(255, 11, 84); }")
        self.Login_button.setObjectName("Login_button")
        self.horizontalLayout.addWidget(self.Login_button)
        self.Registration_button = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(16)
        self.Registration_button.setFont(font)
        self.Registration_button.setStyleSheet(
            "QPushButton { background-color: rgb(125, 127, 255); border-radius: 3px; color: rgb(255, 255, 255); } QPushButton:hover { background-color: rgb(255, 11, 84); }")
        self.Registration_button.setObjectName("Registration_button")
        self.horizontalLayout.addWidget(self.Registration_button)
        self.verticalLayoutWidget = QtWidgets.QWidget(Dialog)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(160, 70, 211, 102))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(20)
        self.verticalLayout.setObjectName("verticalLayout")
        self.UserID_edit = QtWidgets.QLineEdit(self.verticalLayoutWidget)
        self.UserID_edit.setMinimumSize(QtCore.QSize(0, 38))
        self.UserID_edit.setMaximumSize(QtCore.QSize(16777215, 38))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.UserID_edit.setFont(font)
        self.UserID_edit.setText("")
        self.UserID_edit.setDragEnabled(False)
        self.UserID_edit.setReadOnly(False)
        self.UserID_edit.setClearButtonEnabled(True)
        self.UserID_edit.setObjectName("UserID_edit")
        self.verticalLayout.addWidget(self.UserID_edit)
        self.Password_edit = QtWidgets.QLineEdit(self.verticalLayoutWidget)
        self.Password_edit.setMinimumSize(QtCore.QSize(0, 38))
        self.Password_edit.setMaximumSize(QtCore.QSize(16777215, 38))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.Password_edit.setFont(font)
        self.Password_edit.setText("")
        self.Password_edit.setEchoMode(QtWidgets.QLineEdit.PasswordEchoOnEdit)
        self.Password_edit.setObjectName("Password_edit")
        # 设置输入密码框
        self.Password_edit.setEchoMode(QLineEdit.Password)
        self.verticalLayout.addWidget(self.Password_edit)
        self.verticalLayoutWidget_2 = QtWidgets.QWidget(Dialog)
        self.verticalLayoutWidget_2.setGeometry(QtCore.QRect(20, 70, 140, 101))
        self.verticalLayoutWidget_2.setObjectName("verticalLayoutWidget_2")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_2)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setSpacing(20)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.UserID_label = QtWidgets.QLabel(self.verticalLayoutWidget_2)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 120, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        self.UserID_label.setPalette(palette)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(15)
        font.setBold(True)
        font.setItalic(False)
        font.setUnderline(False)
        font.setWeight(50)
        font.setStrikeOut(False)
        self.UserID_label.setFont(font)
        self.UserID_label.setTextFormat(QtCore.Qt.AutoText)
        self.UserID_label.setAlignment(QtCore.Qt.AlignCenter)
        self.UserID_label.setObjectName("UserID_label")
        self.verticalLayout_3.addWidget(self.UserID_label)
        self.Password_label = QtWidgets.QLabel(self.verticalLayoutWidget_2)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 120, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        self.Password_label.setPalette(palette)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(15)
        self.Password_label.setFont(font)
        self.Password_label.setStyleSheet("")
        self.Password_label.setAlignment(QtCore.Qt.AlignCenter)
        self.Password_label.setObjectName("Password_label")
        self.verticalLayout_3.addWidget(self.Password_label)
        self.label = QtWidgets.QLabel(Dialog)
        self.label.setGeometry(QtCore.QRect(140, 10, 131, 41))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 120, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        self.label.setPalette(palette)
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "扫雷游戏登陆界面"))
        self.Login_button.setText(_translate("Dialog", "登录"))
        self.Registration_button.setText(_translate("Dialog", "注册"))
        self.UserID_label.setText(_translate("Dialog", "帐号:"))
        self.Password_label.setText(_translate("Dialog", "密码:"))
        self.label.setText(_translate("Dialog", "登录界面"))

        self.Login_button.clicked.connect(self.login_judge)
        self.Registration_button.clicked.connect(self.jump_to_registration)

    # 判断输入的账号密码是否正确
    def login_judge(self):
        if len(self.UserID_edit.text()) == 8 or len(self.UserID_edit.text()) == 9:
            if len(self.Password_edit.text()) >= 6:
                if len(self.UserID_edit.text()) == 8:  # 普通玩家
                    # 向服务器发送登陆请求，返回得到登陆是否成功的信息
                    tcp_client_socket.send("100 " + self.UserID_edit.text() + " " + self.Password_edit.text())
                    data_list_100 = tcp_client_socket.rec().split()
                    if data_list_100[0] == "101":
                        if data_list_100[1] == "1":  # 账号不存在
                            reply = QMessageBox.about(self.form, "提示", "您输入的账号不存在！请重新输入")
                        elif data_list_100[1] == "2":  # 密码错误
                            reply = QMessageBox.about(self.form, "提示", "您输入的密码错误！请重新输入")
                        elif data_list_100[1] == "3":  # 账号在别处登陆，登陆失败
                            reply = QMessageBox.about(self.form, "提示", "账号在别处登陆，登陆失败！")
                        elif data_list_100[1] == "4":  # 登陆成功
                            print("登陆成功")
                            self.form.hide()
                            form1 = MainDialog()
                            ui = Ui_Dialog()
                            ui.setupUi(form1, self.UserID_edit.text())

                            form1.show()
                            form1.exec_()
                            self.form.close()

                        else:  # 通信出错
                            reply = QMessageBox.about(self.form, "提示", "服务器出错")
                    else:
                        reply = QMessageBox.about(self.form, "提示", "服务器出错")
                elif self.UserID_edit.text()[0] == "a":  # 管理员
                    # 向服务器发送登陆请求，返回得到登陆是否成功的信息
                    tcp_client_socket.send("800 " + self.UserID_edit.text() + " " + self.Password_edit.text())
                    data_list_800 = tcp_client_socket.rec().split()
                    if data_list_800[0] == "801":
                        if data_list_800[1] == "1":  # 账号不存在
                            reply = QMessageBox.about(self.form, "提示", "您输入的账号不存在！请重新输入")
                        elif data_list_800[1] == "2":  # 密码错误
                            reply = QMessageBox.about(self.form, "提示", "您输入的密码错误！请重新输入")
                        elif data_list_800[1] == "3":  # 账号在别处登陆，登陆失败
                            reply = QMessageBox.about(self.form, "提示", "账号在别处登陆，登陆失败！")
                        elif data_list_800[1] == "4":  # 登陆成功
                            username = data_list_800[2]
                            is_super = data_list_800[3]
                            print("管理员登陆成功")
                            self.form.hide()
                            form1 = MainDialog()
                            ui = AdministratorsMainUI()
                            ui.setupUi(form1, self.UserID_edit.text(), username, is_super)
                            form1.show()
                            form1.exec_()
                            self.form.close()

                        else:  # 通信出错
                            reply = QMessageBox.about(self.form, "提示", "服务器出错")
                    else:
                        reply = QMessageBox.about(self.form, "提示", "服务器出错")
                else:
                    reply = QMessageBox.about(self.form, "提示", "您输入的账号不存在！请重新输入")
            else:
                reply = QMessageBox.about(self.form, "提示", "您输入的密码过短（至少6位）！请重新输入")
        else:
            reply = QMessageBox.about(self.form, "提示", "您输入的账号长度有误！请重新输入")

    # 跳转去注册界面
    def jump_to_registration(self):
        self.form.hide()
        form1 = myDialog()
        ui = RegisDialog()
        ui.setupUi(form1)
        form1.show()
        form1.exec_()
        self.form.show()


if __name__ == "__main__":
    # 连接服务器
    tcp_client_socket.conn()

    app = QApplication(sys.argv)
    form = myDialog()
    ui = Login_Dialog()
    ui.setupUi(form)
    form.show()
    app.exec_()
    tcp_client_socket.disconn()  # 断开连接
    sys.exit()
