# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Registration.ui'
#
# Created by: PyQt5 UI code generator 5.15.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.
import random
import sys

from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QMessageBox, QApplication, QDialog, QLineEdit

from TcpClient import tcp_client_socket


class RegisDialog(object):
    def setupUi(self, Dialog):
        self.form = Dialog

        Dialog.setObjectName("Dialog")
        Dialog.resize(390, 320)
        Dialog.setFixedSize(Dialog.width(), Dialog.height())
        Dialog.setStyleSheet("#Dialog{background-color: gainsboro;\n"
                             "border-image: url(icon/login.jpg);}")
        self.verticalLayoutWidget = QtWidgets.QWidget(Dialog)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(150, 80, 231, 158))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(15)
        self.verticalLayout.setObjectName("verticalLayout")
        self.UserName_edit = QtWidgets.QLineEdit(self.verticalLayoutWidget)
        self.UserName_edit.setMinimumSize(QtCore.QSize(209, 38))
        self.UserName_edit.setMaximumSize(QtCore.QSize(209, 38))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.UserName_edit.setFont(font)
        self.UserName_edit.setText("")
        self.UserName_edit.setDragEnabled(False)
        self.UserName_edit.setReadOnly(False)
        self.UserName_edit.setClearButtonEnabled(True)
        self.UserName_edit.setObjectName("UserID_edit")
        self.verticalLayout.addWidget(self.UserName_edit)
        self.Password_edit = QtWidgets.QLineEdit(self.verticalLayoutWidget)
        self.Password_edit.setMinimumSize(QtCore.QSize(209, 38))
        self.Password_edit.setMaximumSize(QtCore.QSize(209, 38))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.Password_edit.setFont(font)
        self.Password_edit.setText("")
        self.Password_edit.setDragEnabled(False)
        self.Password_edit.setReadOnly(False)
        self.Password_edit.setClearButtonEnabled(True)
        self.Password_edit.setObjectName("UserID_edit_3")
        # 设置输入密码框
        self.Password_edit.setEchoMode(QLineEdit.Password)
        self.verticalLayout.addWidget(self.Password_edit)
        self.Password_edit_2 = QtWidgets.QLineEdit(self.verticalLayoutWidget)
        self.Password_edit_2.setMinimumSize(QtCore.QSize(209, 38))
        self.Password_edit_2.setMaximumSize(QtCore.QSize(209, 38))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.Password_edit_2.setFont(font)
        self.Password_edit_2.setText("")
        self.Password_edit_2.setDragEnabled(False)
        self.Password_edit_2.setReadOnly(False)
        self.Password_edit_2.setClearButtonEnabled(True)
        self.Password_edit_2.setObjectName("UserID_edit_2")
        # 设置输入密码框
        self.Password_edit_2.setEchoMode(QLineEdit.Password)
        self.verticalLayout.addWidget(self.Password_edit_2)
        self.verticalLayoutWidget_2 = QtWidgets.QWidget(Dialog)
        self.verticalLayoutWidget_2.setGeometry(QtCore.QRect(20, 80, 130, 155))
        self.verticalLayoutWidget_2.setObjectName("verticalLayoutWidget_2")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_2)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setSpacing(12)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.UserName_label = QtWidgets.QLabel(self.verticalLayoutWidget_2)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 120, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        self.UserName_label.setPalette(palette)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(15)
        self.UserName_label.setFont(font)
        self.UserName_label.setTextFormat(QtCore.Qt.AutoText)
        self.UserName_label.setAlignment(QtCore.Qt.AlignCenter)
        self.UserName_label.setObjectName("UserName_label")
        self.verticalLayout_3.addWidget(self.UserName_label)
        self.Password_label = QtWidgets.QLabel(self.verticalLayoutWidget_2)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 120, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        self.Password_label.setPalette(palette)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(15)
        self.Password_label.setFont(font)
        self.Password_label.setStyleSheet("")
        self.Password_label.setAlignment(QtCore.Qt.AlignCenter)
        self.Password_label.setObjectName("Password_label")
        self.verticalLayout_3.addWidget(self.Password_label)
        self.Password_label_2 = QtWidgets.QLabel(self.verticalLayoutWidget_2)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 120, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        self.Password_label_2.setPalette(palette)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(15)
        self.Password_label_2.setFont(font)
        self.Password_label_2.setStyleSheet("")
        self.Password_label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.Password_label_2.setObjectName("Password_label_2")
        self.verticalLayout_3.addWidget(self.Password_label_2)
        self.Registration_button = QtWidgets.QPushButton(Dialog)
        self.Registration_button.setEnabled(True)
        self.Registration_button.setGeometry(QtCore.QRect(130, 260, 130, 35))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(16)
        self.Registration_button.setFont(font)
        self.Registration_button.setStyleSheet(
            "QPushButton { background-color: rgb(125, 127, 255); border-radius: 3px; color: rgb(255, 255, 255); } QPushButton:hover { background-color: rgb(255, 11, 84); }")
        self.Registration_button.setObjectName("Registration_button")
        self.label = QtWidgets.QLabel(Dialog)
        self.label.setGeometry(QtCore.QRect(130, 20, 130, 41))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 120, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        self.label.setPalette(palette)
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "注册"))
        self.UserName_label.setText(_translate("Dialog", "用户名:"))
        self.Password_label.setText(_translate("Dialog", "密码:"))
        self.Password_label_2.setText(_translate("Dialog", "确认密码:"))
        self.Registration_button.setText(_translate("Dialog", "确认注册"))
        self.label.setText(_translate("Dialog", "注册界面"))

        self.Registration_button.clicked.connect(self.judge)

    # 判断信息是否正确输入
    def judge(self):
        if len(self.UserName_edit.text()) > 0 and len(self.UserName_edit.text()) < 16:
            if len(self.Password_edit.text()) >= 6 and self.Password_edit.text() == self.Password_edit_2.text():
                reply = QMessageBox.information(self.form, '确认你的账户信息',
                                                '您的用户名为：' + self.UserName_edit.text()
                                                + '\n您的密码为：' + self.Password_edit.text()
                                                , QMessageBox.Yes | QMessageBox.No, QMessageBox.Yes)
                if reply == QMessageBox.Yes:
                    self.determine(self.UserName_edit.text(), self.Password_edit.text())
            elif len(self.Password_edit.text()) < 6:
                reply = QMessageBox.about(self.form, "提示", "您输入的密码过短（至少6位）！请重新输入")
            else:
                reply = QMessageBox.about(self.form, "提示", "2次密码输入不一致！请重新输入")
        elif self.UserName_edit.text() == "":
            reply = QMessageBox.about(self.form, "提示", "您的用户名输入为空！请重新输入")
        else:
            reply = QMessageBox.about(self.form, "提示", "您的用户名过长！请勿超过15个字符")

    def determine(self, UserName, Password):
        # todo：向服务器请求注册，服务器随机分配一个用户ID作为登录ID（数字）
        tcp_client_socket.send("102 " + self.UserName_edit.text() + " " + self.Password_edit.text())
        data = tcp_client_socket.rec()
        data_list = data.split()  # 获得服务器发来的消息
        if data_list[0] == "103":
            ID = data_list[1]
            reply = QMessageBox.information(self.form, "注册成功", "注册成功！\n请记住您用于登录的账号为：" + ID + "\n密码为：" + str(Password),
                                            QMessageBox.Ok)
        else:
            reply = QMessageBox.about(self.form, "提示", "服务器出错")

        if reply == QMessageBox.Ok:
            self.form.close()
