# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'test1.ui'
#
# Created by: PyQt5 UI code generator 5.15.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.

import sys
import json
from QDialog import myDialog
from PyQt5.QtWidgets import QApplication, QAbstractItemView, QHeaderView, QListWidget, QMessageBox
from PyQt5 import QtCore, QtGui, QtWidgets
from TcpClient import tcp_client_socket

from ChangePasswordUI import Ui_dialog as change_Password_Dialog


class Ui_Dialog(object):
    def setupUi(self, Dialog, UserID, UserName, BGMSound, ClickSound):
        self.Dialog = Dialog
        self.UserID = UserID
        self.UserName = UserName
        self.BGMSound = BGMSound
        self.ClickSound = ClickSound

        Dialog.setObjectName("Dialog")
        Dialog.resize(421, 395)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(Dialog.sizePolicy().hasHeightForWidth())
        Dialog.setSizePolicy(sizePolicy)
        self.label = QtWidgets.QLabel(Dialog)
        self.label.setGeometry(QtCore.QRect(30, 10, 381, 61))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        self.label.setAlignment(QtCore.Qt.AlignLeading | QtCore.Qt.AlignLeft | QtCore.Qt.AlignVCenter)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(Dialog)
        self.label_2.setGeometry(QtCore.QRect(30, 70, 91, 41))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_2.sizePolicy().hasHeightForWidth())
        self.label_2.setSizePolicy(sizePolicy)
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(Dialog)
        self.label_3.setGeometry(QtCore.QRect(30, 240, 101, 51))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_3.sizePolicy().hasHeightForWidth())
        self.label_3.setSizePolicy(sizePolicy)
        self.label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_3.setObjectName("label_3")
        self.horizontalSlider = QtWidgets.QSlider(Dialog)
        self.horizontalSlider.setGeometry(QtCore.QRect(120, 130, 201, 31))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.horizontalSlider.sizePolicy().hasHeightForWidth())
        self.horizontalSlider.setSizePolicy(sizePolicy)
        self.horizontalSlider.setSliderPosition(self.BGMSound)
        self.horizontalSlider.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider.setTickPosition(QtWidgets.QSlider.TicksBothSides)
        self.horizontalSlider.setObjectName("horizontalSlider")
        self.soundValue = QtWidgets.QLabel(Dialog)
        self.soundValue.setGeometry(QtCore.QRect(330, 130, 71, 31))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.soundValue.sizePolicy().hasHeightForWidth())
        self.soundValue.setSizePolicy(sizePolicy)
        self.soundValue.setAlignment(QtCore.Qt.AlignCenter)
        self.soundValue.setObjectName("soundValue")
        self.pushButton = QtWidgets.QPushButton(Dialog)
        self.pushButton.setGeometry(QtCore.QRect(170, 260, 111, 31))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton.sizePolicy().hasHeightForWidth())
        self.pushButton.setSizePolicy(sizePolicy)
        self.pushButton.setObjectName("pushButton")
        self.buttonBox = QtWidgets.QDialogButtonBox(Dialog)
        self.buttonBox.setGeometry(QtCore.QRect(80, 320, 231, 51))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.buttonBox.sizePolicy().hasHeightForWidth())
        self.buttonBox.setSizePolicy(sizePolicy)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel | QtWidgets.QDialogButtonBox.Save)
        self.buttonBox.setCenterButtons(True)
        self.buttonBox.setObjectName("buttonBox")
        self.label_4 = QtWidgets.QLabel(Dialog)
        self.label_4.setGeometry(QtCore.QRect(50, 140, 54, 18))
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(Dialog)
        self.label_5.setGeometry(QtCore.QRect(50, 200, 54, 18))
        self.label_5.setObjectName("label_5")
        self.horizontalSlider_2 = QtWidgets.QSlider(Dialog)
        self.horizontalSlider_2.setGeometry(QtCore.QRect(120, 190, 201, 31))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.horizontalSlider_2.sizePolicy().hasHeightForWidth())
        self.horizontalSlider_2.setSizePolicy(sizePolicy)
        self.horizontalSlider_2.setSliderPosition(self.ClickSound)
        self.horizontalSlider_2.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider_2.setTickPosition(QtWidgets.QSlider.TicksBothSides)
        self.horizontalSlider_2.setObjectName("horizontalSlider_2")
        self.soundValue_2 = QtWidgets.QLabel(Dialog)
        self.soundValue_2.setGeometry(QtCore.QRect(330, 190, 71, 31))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.soundValue_2.sizePolicy().hasHeightForWidth())
        self.soundValue_2.setSizePolicy(sizePolicy)
        self.soundValue_2.setAlignment(QtCore.Qt.AlignCenter)
        self.soundValue_2.setObjectName("soundValue_2")

        self.retranslateUi(Dialog)
        self.horizontalSlider.valueChanged['int'].connect(self.BGMSoundChange)
        self.horizontalSlider_2.valueChanged['int'].connect(self.ClickSoundChange)

        self.pushButton.clicked.connect(self.passwordChange)
        self.buttonBox.accepted.connect(self.saveSettings)
        self.buttonBox.rejected.connect(Dialog.close)

        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "设置"))
        self.label.setText(_translate("Dialog", "用户名：" + self.UserName))
        self.label_2.setText(_translate("Dialog", "音量设置："))
        self.label_4.setText(_translate("Dialog", "音乐："))
        self.label_5.setText(_translate("Dialog", "音效："))
        self.soundValue.setText(_translate("Dialog", str(self.BGMSound)))
        self.soundValue_2.setText(_translate("Dialog", str(self.ClickSound)))
        self.label_3.setText(_translate("Dialog", "账号设置："))
        self.pushButton.setText(_translate("Dialog", "更改密码"))

    def BGMSoundChange(self, i):
        self.soundValue.setText(str(i))
        self.BGMSound = i

    def ClickSoundChange(self, i):
        self.soundValue_2.setText(str(i))
        self.ClickSound = i

    def passwordChange(self):
        self.Dialog.setEnabled(False)

        form1 = myDialog()
        form1.setWindowModality(2)  # 使本窗口无法选中

        ui = change_Password_Dialog()  # 更改密码窗口
        ui.setupUi(form1, self.UserID)
        form1.show()
        form1.exec_()
        self.Dialog.setEnabled(True)

    def saveSettings(self):
        # 向服务器请求保存音量设置
        tcp_client_socket.send(
            "704 " + self.UserID + ' ' + str(self.BGMSound) + ' ' + str(self.ClickSound))  # todo:bug!!!!

        data_list_705 = tcp_client_socket.rec()

        if data_list_705 == "705a":
            self.Dialog.close()
