# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ShopDataAdmin.ui'
#
# Created by: PyQt5 UI code generator 5.15.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.
from functools import partial

from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtCore import QSize
from PyQt5.QtWidgets import QAbstractItemView, QMessageBox
from TcpClient import tcp_client_socket
import urllib.request

from FlowLayout import FlowLayout


class Ui_Dialog(object):
    def setupUi(self, Dialog, administratorsID):
        self.path = "icon"
        self.form = Dialog
        self.administratorsID = administratorsID
        self.skinlist = []
        self.toolsurl = ""
        self.toolsprice = ""

        Dialog.setObjectName("Dialog")
        Dialog.resize(973, 653)
        self.label_1 = QtWidgets.QLabel(Dialog)
        self.label_1.setGeometry(QtCore.QRect(20, 20, 161, 31))
        font = QtGui.QFont()
        font.setFamily("华文行楷")
        font.setPointSize(15)
        self.label_1.setFont(font)
        self.label_1.setObjectName("label_1")
        self.line = QtWidgets.QFrame(Dialog)
        self.line.setGeometry(QtCore.QRect(460, 10, 20, 631))
        self.line.setFrameShape(QtWidgets.QFrame.VLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.label_2 = QtWidgets.QLabel(Dialog)
        self.label_2.setGeometry(QtCore.QRect(490, 20, 161, 31))
        font = QtGui.QFont()
        font.setFamily("华文行楷")
        font.setPointSize(15)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.label_addskin = QtWidgets.QLabel(Dialog)
        self.label_addskin.setGeometry(QtCore.QRect(500, 60, 311, 21))
        self.label_addskin.setObjectName("label_addskin")
        self.pushButton_addskin = QtWidgets.QPushButton(Dialog)
        self.pushButton_addskin.setGeometry(QtCore.QRect(880, 120, 71, 21))
        self.pushButton_addskin.setObjectName("pushButton_addskin")
        self.lineEdit_addskinurl = QtWidgets.QLineEdit(Dialog)
        self.lineEdit_addskinurl.setGeometry(QtCore.QRect(570, 90, 381, 21))
        self.lineEdit_addskinurl.setObjectName("lineEdit_addskinurl")
        self.label_addskinurl = QtWidgets.QLabel(Dialog)
        self.label_addskinurl.setGeometry(QtCore.QRect(500, 90, 71, 21))
        self.label_addskinurl.setObjectName("label_addskinurl")
        self.label_addskinprice = QtWidgets.QLabel(Dialog)
        self.label_addskinprice.setGeometry(QtCore.QRect(500, 120, 71, 21))
        self.label_addskinprice.setObjectName("label_addskinprice")
        self.lineEdit_addskinprice = QtWidgets.QLineEdit(Dialog)
        self.lineEdit_addskinprice.setGeometry(QtCore.QRect(570, 120, 291, 21))
        self.lineEdit_addskinprice.setObjectName("lineEdit_addskinprice")
        self.label_deleteskinid = QtWidgets.QLabel(Dialog)
        self.label_deleteskinid.setGeometry(QtCore.QRect(500, 200, 71, 21))
        self.label_deleteskinid.setObjectName("label_deleteskinid")
        self.label_deleteskin = QtWidgets.QLabel(Dialog)
        self.label_deleteskin.setGeometry(QtCore.QRect(500, 170, 311, 21))
        self.label_deleteskin.setObjectName("label_deleteskin")
        self.lineEdit_deleteskin = QtWidgets.QLineEdit(Dialog)
        self.lineEdit_deleteskin.setGeometry(QtCore.QRect(570, 200, 291, 21))
        self.lineEdit_deleteskin.setObjectName("lineEdit_deleteskin")
        self.line_2 = QtWidgets.QFrame(Dialog)
        self.line_2.setGeometry(QtCore.QRect(470, 150, 501, 16))
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.pushButton_deleteskin = QtWidgets.QPushButton(Dialog)
        self.pushButton_deleteskin.setGeometry(QtCore.QRect(880, 200, 71, 21))
        self.pushButton_deleteskin.setObjectName("pushButton_deleteskin")
        self.line_3 = QtWidgets.QFrame(Dialog)
        self.line_3.setGeometry(QtCore.QRect(470, 230, 501, 16))
        self.line_3.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_3.setObjectName("line_3")
        self.label_changeskinprice = QtWidgets.QLabel(Dialog)
        self.label_changeskinprice.setGeometry(QtCore.QRect(500, 350, 71, 21))
        self.label_changeskinprice.setObjectName("label_changeskinprice")
        self.label_changeskinurl = QtWidgets.QLabel(Dialog)
        self.label_changeskinurl.setGeometry(QtCore.QRect(500, 320, 71, 21))
        self.label_changeskinurl.setObjectName("label_changeskinurl")
        self.lineEdit_changeskinprice = QtWidgets.QLineEdit(Dialog)
        self.lineEdit_changeskinprice.setGeometry(QtCore.QRect(570, 350, 291, 21))
        self.lineEdit_changeskinprice.setObjectName("lineEdit_changeskinprice")
        self.label_changeskin = QtWidgets.QLabel(Dialog)
        self.label_changeskin.setGeometry(QtCore.QRect(500, 260, 311, 21))
        self.label_changeskin.setObjectName("label_changeskin")
        self.pushButton_changeskin = QtWidgets.QPushButton(Dialog)
        self.pushButton_changeskin.setGeometry(QtCore.QRect(880, 350, 71, 21))
        self.pushButton_changeskin.setObjectName("pushButton_changeskin")
        self.lineEdit_changeskinurl = QtWidgets.QLineEdit(Dialog)
        self.lineEdit_changeskinurl.setGeometry(QtCore.QRect(570, 320, 381, 21))
        self.lineEdit_changeskinurl.setObjectName("lineEdit_changeskinurl")
        self.lineEdit_changeskinid = QtWidgets.QLineEdit(Dialog)
        self.lineEdit_changeskinid.setGeometry(QtCore.QRect(570, 290, 291, 21))
        self.lineEdit_changeskinid.setObjectName("lineEdit_changeskinid")
        self.label_changeskinid = QtWidgets.QLabel(Dialog)
        self.label_changeskinid.setGeometry(QtCore.QRect(500, 290, 71, 21))
        self.label_changeskinid.setObjectName("label_changeskinid")
        self.line_4 = QtWidgets.QFrame(Dialog)
        self.line_4.setGeometry(QtCore.QRect(470, 510, 501, 16))
        self.line_4.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_4.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_4.setObjectName("line_4")
        self.label_changetool = QtWidgets.QLabel(Dialog)
        self.label_changetool.setGeometry(QtCore.QRect(500, 540, 311, 21))
        self.label_changetool.setObjectName("label_changetool")
        self.label_changetoolurl = QtWidgets.QLabel(Dialog)
        self.label_changetoolurl.setGeometry(QtCore.QRect(500, 570, 71, 21))
        self.label_changetoolurl.setObjectName("label_changetoolurl")
        self.lineEdit_changetoolprice = QtWidgets.QLineEdit(Dialog)
        self.lineEdit_changetoolprice.setGeometry(QtCore.QRect(570, 600, 291, 21))
        self.lineEdit_changetoolprice.setObjectName("lineEdit_changetoolprice")
        self.lineEdit_changetoolurl = QtWidgets.QLineEdit(Dialog)
        self.lineEdit_changetoolurl.setGeometry(QtCore.QRect(570, 570, 381, 21))
        self.lineEdit_changetoolurl.setObjectName("lineEdit_changetoolurl")
        self.pushButton_changetool = QtWidgets.QPushButton(Dialog)
        self.pushButton_changetool.setGeometry(QtCore.QRect(880, 600, 71, 21))
        self.pushButton_changetool.setObjectName("pushButton_changetool")
        self.label_changetoolprice = QtWidgets.QLabel(Dialog)
        self.label_changetoolprice.setGeometry(QtCore.QRect(500, 600, 71, 21))
        self.label_changetoolprice.setObjectName("label_changetoolprice")
        self.label_3 = QtWidgets.QLabel(Dialog)
        self.label_3.setGeometry(QtCore.QRect(20, 510, 161, 31))
        font = QtGui.QFont()
        font.setFamily("华文行楷")
        font.setPointSize(15)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.listWidget_tool = QtWidgets.QListWidget(Dialog)
        self.listWidget_tool.setGeometry(QtCore.QRect(20, 550, 431, 81))
        self.listWidget_tool.setObjectName("listView_tool")

        self.listWidget_skin = QtWidgets.QListWidget(Dialog)
        self.listWidget_skin.setGeometry(QtCore.QRect(20, 60, 431, 431))
        self.listWidget_skin.setObjectName("listView_skin")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

        self.update_skin()

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.label_1.setText(_translate("Dialog", "商城皮肤查询"))
        self.label_2.setText(_translate("Dialog", "皮肤数据修改"))
        self.label_addskin.setText(_translate("Dialog", "增加皮肤"))
        self.pushButton_addskin.setText(_translate("Dialog", "确认"))
        self.lineEdit_addskinurl.setPlaceholderText(_translate("Dialog", "示例:http://p15.qhmsg.com/21f5bf45a5.jpg"))
        self.label_addskinurl.setText(_translate("Dialog", "皮肤url："))
        self.label_addskinprice.setText(_translate("Dialog", "皮肤价格："))
        self.lineEdit_addskinprice.setPlaceholderText(_translate("Dialog", "示例:200"))
        self.label_deleteskinid.setText(_translate("Dialog", "皮肤ID："))
        self.label_deleteskin.setText(_translate("Dialog", "删除皮肤"))
        self.lineEdit_deleteskin.setPlaceholderText(_translate("Dialog", "（4位ID）示例:1003"))
        self.pushButton_deleteskin.setText(_translate("Dialog", "确认"))
        self.label_changeskinprice.setText(_translate("Dialog", "皮肤价格："))
        self.label_changeskinurl.setText(_translate("Dialog", "皮肤url："))
        self.lineEdit_changeskinprice.setPlaceholderText(_translate("Dialog", "示例:200"))
        self.label_changeskin.setText(_translate("Dialog", "修改已有皮肤"))
        self.pushButton_changeskin.setText(_translate("Dialog", "确认"))
        self.lineEdit_changeskinurl.setPlaceholderText(_translate("Dialog", "示例:http://p15.qhmsg.com/21f5bf45a5.jpg"))
        self.lineEdit_changeskinid.setPlaceholderText(_translate("Dialog", "（4位ID）示例:1003"))
        self.label_changeskinid.setText(_translate("Dialog", "皮肤ID："))
        self.label_changetool.setText(_translate("Dialog", "修改道具"))
        self.label_changetoolurl.setText(_translate("Dialog", "道具url："))
        self.lineEdit_changetoolprice.setPlaceholderText(_translate("Dialog", "示例:200"))
        self.lineEdit_changetoolurl.setPlaceholderText(_translate("Dialog", "示例:http://p15.qhmsg.com/21f5bf45a5.jpg"))
        self.pushButton_changetool.setText(_translate("Dialog", "确认"))
        self.label_changetoolprice.setText(_translate("Dialog", "道具价格："))
        self.label_3.setText(_translate("Dialog", "商城道具查询"))

        self.pushButton_addskin.clicked.connect(self.add_skin)
        self.pushButton_deleteskin.clicked.connect(self.delete_skin)
        self.pushButton_changeskin.clicked.connect(self.change_skin)
        self.pushButton_changetool.clicked.connect(self.change_tools)

    def update_skin(self):
        self.listWidget_skin.clear()
        self.listWidget_tool.clear()
        self.skinlist.clear()
        tcp_client_socket.send("808 " + self.administratorsID)
        data_list = tcp_client_socket.rec().split()
        print(data_list)
        if data_list[0] == "809":
            # 将商城信息存入列表skinlist中
            self.toolsurl = data_list[1]
            urllib.request.urlretrieve(data_list[1],
                                       filename=self.path + "/admin_tools.jpg")  # 下载图片
            self.toolsprice = data_list[2]
            for i in range(int(len(data_list) / 3 - 1)):
                temp = []
                temp.append(data_list[i * 3 + 3])
                temp.append(data_list[i * 3 + 4])
                urllib.request.urlretrieve(data_list[i * 3 + 4],
                                           filename=self.path + "/admin_skin_" + data_list[i * 3 + 3] + ".jpg")  # 下载图片
                temp.append(data_list[i * 3 + 5])
                self.skinlist.append(temp)

            for j in self.skinlist:
                skinID_button = QtWidgets.QPushButton(j[0])
                skinID_button.setFlat(True)
                skinID_button.setMinimumSize(50, 100)

                picture_button = QtWidgets.QPushButton()
                icon = QtGui.QIcon()
                icon.addPixmap(QtGui.QPixmap(self.path + "/admin_skin_" + j[0] + ".jpg"), QtGui.QIcon.Normal,
                               QtGui.QIcon.Off)
                picture_button.setIcon(icon)
                picture_button.setIconSize(QtCore.QSize(150, 100))
                picture_button.setFlat(True)

                skinprice_button = QtWidgets.QPushButton(j[2] + "金币")
                skinprice_button.setFlat(True)
                skinprice_button.setMinimumSize(50, 100)

                picture_button.clicked.connect(partial(self.click1, j[2]))

                # 设置每一行的布局
                layout = FlowLayout()
                layout.addWidget(skinID_button)
                layout.addWidget(picture_button)
                layout.addWidget(skinprice_button)

                # 给每一行加入上面的布局
                widget = QtWidgets.QDialog(self.listWidget_skin)
                item = QtWidgets.QListWidgetItem(self.listWidget_skin)
                item.setSizeHint(QSize(301, 140))

                widget.setLayout(layout)
                self.listWidget_skin.addItem(item)
                self.listWidget_skin.setItemWidget(item, widget)

            # 查看道具
            picture_button = QtWidgets.QPushButton()
            icon = QtGui.QIcon()
            icon.addPixmap(QtGui.QPixmap(self.path + "/admin_tools.jpg"), QtGui.QIcon.Normal,
                           QtGui.QIcon.Off)
            picture_button.setIcon(icon)
            picture_button.setIconSize(QtCore.QSize(150, 100))
            picture_button.setFlat(True)

            toolsprice_button = QtWidgets.QPushButton(self.toolsprice + "金币")
            toolsprice_button.setFlat(True)
            toolsprice_button.setMinimumSize(50, 100)

            # 设置每一行的布局
            layout = FlowLayout()
            layout.addWidget(picture_button)
            layout.addWidget(toolsprice_button)

            # 给每一行加入上面的布局
            widget = QtWidgets.QDialog(self.listWidget_tool)
            item = QtWidgets.QListWidgetItem(self.listWidget_tool)
            item.setSizeHint(QSize(301, 140))

            widget.setLayout(layout)
            self.listWidget_tool.addItem(item)
            self.listWidget_tool.setItemWidget(item, widget)

    def click1(self, price):
        print("czy123 " + price)

    def add_skin(self):
        if self.lineEdit_addskinurl.text() is not None and self.lineEdit_addskinprice.text() is not None:
            if self.lineEdit_addskinprice.text().isdecimal():
                tcp_client_socket.send(
                    "810 " + self.administratorsID + " 1 " + self.lineEdit_addskinurl.text() + " " + self.lineEdit_addskinprice.text())
                data_list = tcp_client_socket.rec().split()
                print(data_list)
                if data_list[0] == "811":
                    if data_list[1] == "1":
                        self.update_skin()
                        reply = QMessageBox.about(self.form, "提示", "增加成功！")
                    else:
                        reply = QMessageBox.about(self.form, "提示", "增加失败！")
            else:
                reply = QMessageBox.about(self.form, "提示", "皮肤价格为数字")
        else:
            reply = QMessageBox.about(self.form, "提示", "皮肤url和皮肤价格不能为空")

    def delete_skin(self):
        if self.lineEdit_deleteskin.text() is not None:
            if self.lineEdit_deleteskin.text().isdecimal() and len(self.lineEdit_deleteskin.text()) == 4:
                tcp_client_socket.send(
                    "810 " + self.administratorsID + " 2 " + self.lineEdit_deleteskin.text())
                data_list = tcp_client_socket.rec().split()
                if data_list[0] == "811":
                    if data_list[1] == "1":
                        self.update_skin()
                        reply = QMessageBox.about(self.form, "提示", "删除成功！")
                    else:
                        reply = QMessageBox.about(self.form, "提示", "删除失败！")
            else:
                reply = QMessageBox.about(self.form, "提示", "皮肤ID必须是4位数字")
        else:
            reply = QMessageBox.about(self.form, "提示", "皮肤ID不能为空")

    def change_skin(self):
        if self.lineEdit_changeskinid.text() is not None and self.lineEdit_changeskinurl.text() is not None and self.lineEdit_changeskinprice.text() is not None:
            if self.lineEdit_changeskinid.text().isdecimal() and len(
                    self.lineEdit_changeskinid.text()) == 4 and self.lineEdit_changeskinprice.text().isdecimal():
                tcp_client_socket.send(
                    "810 " + self.administratorsID + " 3 " + self.lineEdit_changeskinid.text() + " " + self.lineEdit_changeskinurl.text() + " " + self.lineEdit_changeskinprice.text())
                data_list = tcp_client_socket.rec().split()
                if data_list[0] == "811":
                    if data_list[1] == "1":
                        self.update_skin()
                        reply = QMessageBox.about(self.form, "提示", "修改成功！")
                    else:
                        reply = QMessageBox.about(self.form, "提示", "修改失败！")
            else:
                reply = QMessageBox.about(self.form, "提示", "输入格式错误，请重新输入")
        else:
            reply = QMessageBox.about(self.form, "提示", "输入不能为空")

    def change_tools(self):
        if self.lineEdit_changetoolurl.text() is not None and self.lineEdit_changetoolprice.text() is not None:
            if self.lineEdit_changetoolprice.text().isdecimal():
                tcp_client_socket.send(
                    "810 " + self.administratorsID + " 4 " + self.lineEdit_changetoolurl.text() + " " + self.lineEdit_changetoolprice.text())
                data_list = tcp_client_socket.rec().split()
                if data_list[0] == "811":
                    if data_list[1] == "1":
                        self.update_skin()
                        reply = QMessageBox.about(self.form, "提示", "修改成功！")
                    else:
                        reply = QMessageBox.about(self.form, "提示", "修改失败！")
            else:
                reply = QMessageBox.about(self.form, "提示", "输入格式错误，请重新输入")
        else:
            reply = QMessageBox.about(self.form, "提示", "输入不能为空")


if __name__ == "__main__":
    import sys

    tcp_client_socket.conn()
    app = QtWidgets.QApplication(sys.argv)
    widget = QtWidgets.QWidget()
    ui = Ui_Dialog()
    ui.setupUi(widget, "12341234")
    widget.show()
    sys.exit(app.exec_())
